- hosts: ansible
  tasks:
  - name: httpd is installed
    yum:
     name: httpd
     state: present
  - name: httpd is running and enabled
    service:
     name: httpd
     state: started
     enabled: yes
